### ISSUE TITLE
XHR error angular2-schema-form not found (I'm using rc.5)

### ISSUE THREAD

**Issue by estradamarkie** [makinacorpus/angular2-schema-form#28]
Hi,

I'm trying to use this on my application, I followed the installation on the main page and its giving me 

`Error: Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-schema-form(…)`

I'm using SystemJs Config and I also tried adding it in my config js but then it throws an error regarding lodash and validator.

`var map = { 'angular2-schema-form': 'node_modules/angular2-schema-form' }`
`var packages = {  'angular2-schema-form': { main: './dist/index.js', defaultExtension: 'js' }`

Can you shed a light on this, please.

Is it possible to have a guide for rc.5 and for systemjs config users?

Thanks

**Comment by ebrehault** [comment]
You should definitely upgrade to Angular 2.0 final.

Note: To set up a clean ng2 project, I recommend to use the ng CLI.

**Comment by estradamarkie** [comment]
Thanks for the reply, I'm using 2.0.0-rc.5.

Oh I see, I've pretty much setup all my stuff using sysmtemjs.config.js. Is it gonna be easy to change from that to CLI? Because when I setup my application I was just following the guide from ng2 site quickstart.

**Comment by estradamarkie** [comment]
Will see if upgrading to 2.0 final will fix the issue, if so then ill stick with that for a while before moving to CLI. as I have pretty much completed my demo.

**Comment by estradamarkie** [comment]
@ebrehault will angular2-schema-form still work on rc4?

**Comment by ebrehault** [comment]
Not the current master or last release.
But if you go back to 1.0.0-alpha.16, it should work.

**Comment by estradamarkie** [comment]
sorry I meant 2.0.0-rc.4

**Comment by ebrehault** [comment]
Yes that's what I meant too :) : angular2-schema-form 1.0.0-alpha.16 should work with Angular 2.0.0-rc.4

**Comment by estradamarkie** [comment]
Oh right :), cool thanks.

Though I'm getting this error using .16 any idea about this?

`node_modules/angular2-schema-form/dist/src/schema-form/model/formproperty.d.ts(31,14): error TS1005: '=' expected.
node_modules/angular2-schema-form/dist/src/schema-form/model/formproperty.d.ts(31,19): error TS1005: ';' expected.`

**Comment by ebrehault** [comment]
Yeah, well I do not know, at the time we were struggling in the infinite RC/breaking changes/upgrades nightmare so...
Give a try to angular2-schema-form 1.0.0-alpha.15 :)

**Comment by estradamarkie** [comment]
Oh right yeah seems like it, even alpha.15 is giving me the same error. I guess I will just have to update.

**Comment by fbessou** [comment]
Are you sure you have installed .16 ? At this time the file "formproperty.ts" didn't exist.
